#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# strip leading slash if present in set variable
if [[ -n "$CONTEXT_PATH" ]]; then
    CONTEXT_PATH="${CONTEXT_PATH#/}"
fi

# set url base to / if variable not set, readding leading slash if variable is set.
URL_BASE="/${CONTEXT_PATH}"

# add option to pass runtime arguments
IFS=" " read -r -a RUN_ARRAY <<< "$JAVA_OPTS"

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 4040" \
        cd "${BOOKSONIC_AIR_HOME}" s6-setuidgid abc java \
            -Dairsonic.defaultMusicFolder=/music \
            -Dairsonic.defaultPlaylistFolder=/playlists \
            -Dairsonic.defaultPodcastFolder=/podcasts \
            -Dairsonic.home="${BOOKSONIC_AIR_SETTINGS}" \
            -Djava.awt.headless=true \
            -Djava.io.tmpdir="/run/tomcat.4040" \
            -Dserver.servlet.contextPath="${URL_BASE}" \
            -Dserver.host=0.0.0.0 \
            -Dserver.port=4040 \
            "${RUN_ARRAY[@]}" \
            -jar booksonic.war
