#!/usr/bin/with-contenv bash

mkdir -p "${BOOKSONIC_AIR_SETTINGS}"/transcode

if [[ ! -e "${BOOKSONIC_AIR_SETTINGS}"/transcode/ffmpeg || ! -e  "${BOOKSONIC_AIR_SETTINGS}"/transcode/flac || ! -e "${BOOKSONIC_AIR_SETTINGS}"/transcode/lame  ]]; then
ln -sf /usr/bin/ffmpeg "${BOOKSONIC_AIR_SETTINGS}"/transcode/
ln -sf /usr/bin/flac "${BOOKSONIC_AIR_SETTINGS}"/transcode/
ln -sf /usr/bin/lame "${BOOKSONIC_AIR_SETTINGS}"/transcode/
fi

chown -R abc:abc /config "${BOOKSONIC_AIR_SETTINGS}"  "${BOOKSONIC_AIR_HOME}"
